#!/usr/bin/env python3
"""
Vonex internal-link opportunity scanner.

Scans the public Vonex URL list and reports keyword opportunities where
a relevant Vonex target page is not already linked. It also reports
target pages with no incoming links from the scanned set.

This tool only produces a report. It does not edit vonex.ca.
"""
import csv
import re
from collections import defaultdict
from pathlib import Path
from urllib.parse import urlparse

import requests
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]
URL_FILE = ROOT / "data" / "vonex-pages.csv"
OUT_FILE = ROOT / "reports" / "internal-link-opportunities.md"
HEADERS = {"User-Agent": "Vonex-Internal-Link-Audit/1.0"}
TIMEOUT = 20

KEYWORDS = {
    "printer repair": "https://vonex.ca/printer-repair-saskatoon",
    "printer repairs": "https://vonex.ca/repairs",
    "copier service": "https://vonex.ca/copier-service-saskatoon",
    "managed print": "https://vonex.ca/managed-print",
    "managed print services": "https://vonex.ca/managed-print",
    "printer leasing": "https://vonex.ca/lease-rental",
    "printer lease": "https://vonex.ca/lease-rental",
    "office equipment": "https://vonex.ca/office-equipment",
    "toner": "https://vonex.ca/ink-toner",
    "ink": "https://vonex.ca/ink-toner",
    "Kyocera": "https://vonex.ca/kyocera-authorized-dealer-saskatoon",
    "HP printer service": "https://vonex.ca/hp-printer-service-saskatoon",
    "Lexmark printer service": "https://vonex.ca/lexmark-printer-service-saskatoon",
}

def load_urls():
    with URL_FILE.open(newline="", encoding="utf-8") as f:
        return [row["url"].strip() for row in csv.DictReader(f) if row.get("url")]

def normalize(url):
    p = urlparse(url)
    path = p.path.rstrip("/") or "/"
    return f"{p.scheme}://{p.netloc}{path}"

def fetch(url):
    r = requests.get(url, headers=HEADERS, timeout=TIMEOUT)
    r.raise_for_status()
    return r.text

def parse(html):
    soup = BeautifulSoup(html, "html.parser")
    for tag in soup(["script", "style", "noscript"]):
        tag.decompose()
    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    links = set()
    for a in soup.find_all("a", href=True):
        href = a["href"].strip()
        if href.startswith("https://vonex.ca/"):
            links.add(normalize(href))
    return text, links

def main():
    urls = load_urls()
    pages = {}
    errors = []

    for url in urls:
        try:
            pages[normalize(url)] = parse(fetch(url))
        except Exception as exc:
            errors.append((url, str(exc)))

    incoming = defaultdict(list)
    for source, (_, links) in pages.items():
        for target in links:
            incoming[target].append(source)

    report = [
        "# Vonex Internal Link Opportunities",
        "",
        "Generated by tools/internal-link-builder.py.",
        "",
        "Audit/report only. No website content is changed automatically.",
        "",
        "## Priority opportunities",
        "",
    ]

    seen = set()
    for source, (page_text, links) in pages.items():
        hits = []
        lower = page_text.lower()
        for phrase, target in KEYWORDS.items():
            target = normalize(target)
            if target == source or target in links:
                continue
            if phrase.lower() in lower:
                key = (source, target)
                if key not in seen:
                    seen.add(key)
                    hits.append((phrase, target))
        if hits:
            report.append(f"### {source}")
            for phrase, target in hits[:10]:
                report.append(f"- **{phrase}** -> {target}")
            report.append("")

    report += ["## Target pages with no incoming link from the scanned set", ""]
    for url in sorted(set(pages) - set(incoming)):
        report.append(f"- {url}")

    report += ["", "## Fetch errors", ""]
    if errors:
        for url, error in errors:
            report.append(f"- {url}: {error}")
    else:
        report.append("- None")

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text("\n".join(report) + "\n", encoding="utf-8")
    print(f"Scanned {len(pages)} pages; wrote {OUT_FILE}")

if __name__ == "__main__":
    main()
